
-- Tabela de bloqueios (Férias, Folgas, Manutenção)
CREATE TABLE IF NOT EXISTS erp_instructor_blocks (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  instructor_id BIGINT REFERENCES erp_instructors(id) ON DELETE CASCADE,
  start_date DATE NOT NULL,
  end_date DATE NOT NULL,
  reason TEXT CHECK (reason IN ('vacation', 'sick_leave', 'training', 'other')),
  notes TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  created_by UUID REFERENCES auth.users(id)
);

-- Tabela de preferências avançadas
CREATE TABLE IF NOT EXISTS erp_instructor_preferences (
  instructor_id BIGINT PRIMARY KEY REFERENCES erp_instructors(id) ON DELETE CASCADE,
  max_lessons_per_day INTEGER DEFAULT 8,
  preferred_vehicles BIGINT[], -- Array de IDs dos veículos
  break_duration INTEGER DEFAULT 15, -- Minutos de intervalo entre aulas
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Policies (RLS)
ALTER TABLE erp_instructor_blocks ENABLE ROW LEVEL SECURITY;
ALTER TABLE erp_instructor_preferences ENABLE ROW LEVEL SECURITY;

-- Blocks policies
CREATE POLICY "Enable read access for authenticated users" ON erp_instructor_blocks
  FOR SELECT USING (auth.role() = 'authenticated');

CREATE POLICY "Enable insert for authenticated users" ON erp_instructor_blocks
  FOR INSERT WITH CHECK (auth.role() = 'authenticated');

CREATE POLICY "Enable update for authenticated users" ON erp_instructor_blocks
  FOR UPDATE USING (auth.role() = 'authenticated');

CREATE POLICY "Enable delete for authenticated users" ON erp_instructor_blocks
  FOR DELETE USING (auth.role() = 'authenticated');

-- Preferences policies
CREATE POLICY "Enable read access for authenticated users" ON erp_instructor_preferences
  FOR SELECT USING (auth.role() = 'authenticated');

CREATE POLICY "Enable insert for authenticated users" ON erp_instructor_preferences
  FOR INSERT WITH CHECK (auth.role() = 'authenticated');

CREATE POLICY "Enable update for authenticated users" ON erp_instructor_preferences
  FOR UPDATE USING (auth.role() = 'authenticated');

CREATE POLICY "Enable delete for authenticated users" ON erp_instructor_preferences
  FOR DELETE USING (auth.role() = 'authenticated');
